FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential automake pkg-config libtool bison flex libpcre2-dev

COPY . /repo
WORKDIR /repo
RUN ./autogen.sh
RUN ./configure
RUN make -j8
